import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Nextjs.dev",
    template: "%s - Nextjs.dev",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header>
          <h1>===== Header =====</h1>
          <NavBar />
        </header>
        <main>{children}</main>
        <footer>
          <h2>----- Footer -----</h2>
        </footer>
      </body>
    </html>
  );
}
